[package]
name = "rust-test"
version = "0.1.0"
authors = ["gu <1982775886@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
